# Travis integration
language: Haskell

# Explicitly request container-based infrastructure.
sudo: false

env:
      global:
          - ENCRYPTION_LABEL: "57579b36e4b4"
          - COMMIT_AUTHOR_EMAIL: "frantisek@farka.eu"

cache:
      directories:
            - $HOME/.cabal
            - $HOME/.ghc

before_install:
    - export PATH=$HOME/.cabal/bin/:/usr/local/ghc/$(ghc_find )/bin/:$PATH
    - echo $PATH
    - cat $HOME/.cabal/world
    - cabal update
    - cabal install --dependencies-only cabal-install-1.24.0.0
    - cabal install --dependencies-only cabal-install-1.24.0.0
    - cabal install cabal-install-1.24.0.0
    - hash -r && cabal --version
    - cabal install alex happy
    - hash -r && alex --version && happy --version
    - #cabal install agda-2.5.1.1
    - mkdir ~/.agda
    - wget -nv https://github.com/agda/agda-stdlib/archive/v0.12.tar.gz
    - tar xzf v0.12.tar.gz -C ~/.agda
    - echo ~/.agda/agda-stdlib-0.12/standard-library.agda-lib >> ~/.agda/libraries


install: true


script: true

after_success:
    - #make doc

