# Travis integration
language: Haskell

# Explicitly request container-based infrastructure.
sudo: false


before_install:
    - cabal install cabal-install
    - cabal install agda-2.4.0
    - cabal install agda-stdlib


install: true


after_install:
    - make doc


after_failure:
    - cat /home/travis/.cabal/logs/cabal-install-1.24.0.0.log
