# Travis integration
language: Haskell

# Explicitly request container-based infrastructure.
sudo: false


before_install:
    - export PATH=/home/travis/.cabal/bin/:$PATH
    - cabal install cabal-install-1.22.0.0
    - hash -r
    - cabal install alex happy
    - hash -r
    - cabal install agda
    - cabal install agda-stdlib


install: true


after_install:
    - make doc

