# Travis integration
language: Haskell

# Explicitly request container-based infrastructure.
sudo: false


before_install:
    - cabal install agda-2.4.2
    - cabal install agda-stdlib


install: true


after_install:
    - make doc
